spring.application.name=book-loan-consumer

server.port=8081

# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=book-loan-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.bvd.consumer.model.BookLoan
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# Topic name
kafka.topic.name=book-loans


# OpenTelemetry configuration
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Logging pattern to include trace ID
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]